---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-frontend-deployment
  namespace: jaeger-ns
  labels:
    fico.application.owner: ProgramBlue
    fico.application.name: jaeger-frontend-deploy

spec:
  replicas: 1
  selector:
    matchLabels:
      fico.application.owner: ProgramBlue
      fico.application.name: jaeger-frontend
  template:
    metadata:
      labels:
        fico.application.owner: ProgramBlue
        fico.application.name: jaeger-frontend
    spec:
      containers:
        - name: jaeger-frontend-container
          image: jaeger_frontend_image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: JAEGER_AGENT_HOST
              value: jaeger-service

            - name: JAEGER_AGENT_PORT
              value: "14268"

            - name: BACKEND_HOST
              value: jaeger-backend-service

---

apiVersion: v1
kind: Service
metadata:
  name: jaeger-frontend-service
  namespace: jaeger-ns
  labels:
    fico.application.owner: ProgramBlue
    fico.application.name: jaeger-frontend-svc
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30011
  selector:
    fico.application.owner: ProgramBlue
    fico.application.name: jaeger-frontend