jaegerui:
  name: jaeger-server
  replicas: 1
  image: jaegertracing/all-in-one:1.35

backendApp:
  name: backend-app
  replicas: 1
  image: shaktipp/jaeger_backend_image:latest
  port: 8081

frontendApp:
  name: frontend-app
  replicas: 1
  image: shaktipp/jaeger_frontend_image:latest
  port: 8080

ingress:
  name: jaeger-ingress